### ISSUE TITLE
"select a file" remains open on debian-based system

### ISSUE THREAD

**Issue by jayich** [Spinmob/spinmob#72]
When running:

```python
>>> E_x = sm.data.load()
```

The dialog window remains open.  I'm running this on linux mint.

**Comment by jayich** [comment]
The dialog window is frozen after the file has been selected.  I can load in the file, the window just persists.

**Comment by gregllong** [comment]
@jayich This could be an ipython backend problem. After setting the following in the ipython config file (which can found in `~/.ipython/profile_default/ipython_config.py` after typing `$ ipython profile create` in the terminal):

c.InteractiveShellApp.gui = 'qt'  # this might not be necessary
c.InteractiveShellApp.matplotlib = 'qt'

the problem seems to disappear.

**Comment by jayich** [comment]
@gregllong , good work.
