### ISSUE TITLE
Constants are ignored when a function is supplied to a `fitter` as a callable

### ISSUE THREAD

**Issue by julian-wolf** [Spinmob/spinmob#87]
When a model function is supplied to a `fitter` instance as a string, everything works as expected. Supplying an actual callable function, though, results in constants being ignored (all arguments are treated as parameters). The [inspect][1] module has some metaprogramming stuff that might be helpful in finding a fix—namely, `getargspec` plus some substitution and a lambda could probably be made to do something useful.

[1]: http://docs.python.org/library/inspect.html

**Comment by jayich** [comment]
Having the ability to input functions as well as strings sounds like a nice improvement.  inspect is part of the standard library, which is good.

@jaxankey , what do you think?

**Comment by julian-wolf** [comment]
The functionality for using callables already (mostly) exists; see https://github.com/Spinmob/spinmob/blob/master/_data.py#L1236-L1242

The issue is that, when this is how functions are supplied, they don't seem to "fix" any parameters, even those listed as constants.

**Comment by jayich** [comment]
Right.  Looks like more of a bug that needs to be fixed.

This docstring says it can be a function:
https://github.com/Spinmob/spinmob/blob/master/_data.py#L1142-L1146

**Comment by jaxankey** [comment]
There is no easy way to make the callables work with constants, because it
means you have to redefine the callable; that would add a level of
complexity that is not necessary, especially since it's not needed. I am
thinking of removing the ability to supply callables, because you can
always just supply something like this:

fitter('f(x)', g=dict(f=my_callable))

xoxoxo
Jack

**Comment by julian-wolf** [comment]
That's a good work-around; hadn't thought of that. Rather than disallowing supplying callables all together why not just change
```python
self.f.append(f[n])
self._fnames.append(f[n].__name__)
```
 to something along the lines of
```python
self._globals[f[n].__name__] = f[n]
self.f.append(eval('lambda ' + pstring + ': {}(x)'.format(f[n].__name__), self._globals))
self._fnames.append(f[n].__name__)
```
at https://github.com/Spinmob/spinmob/blob/master/_data.py#L1241-L1242? Would that fix the constants issue?

(I haven't tested this)

**Comment by jaxankey** [comment]
The goal being to convert the callable into a string function at the
outset? That could work. Test it :)

-Jack

Sent from sender's phone with typos. Sender not liable for inflammatory
autocorrects.

On Feb 5, 2017 11:27 PM, "Julian Wolf" <notifications@github.com> wrote:

That's a good work-around; hadn't thought of that. Rather than disallowing
supplying callables all together why not just change

self.f.append(f[n])self._fnames.append(f[n].__name__)

to something along the lines of

self._globals[f[n].__name__] = f[n]self.f.append(eval('lambda ' +
pstring + ': {}(x)'.format(f[n].__name__),
self._globals))self._fnames.append(f[n].__name__)

at https://github.com/Spinmob/spinmob/blob/master/_data.py#L1241-L1242?
Would that fix the constants issue?

(I haven't tested this)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Spinmob/spinmob/issues/87#issuecomment-277584197>, or mute
the thread
